apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ include "pod-identity.fullname" . }}
spec:
  azureIdentity: {{ .Values.identityName }}
  selector: {{ .Values.identityName }}
